# Copyright (c) 2016 Copyright Holder All Rights Reserved.

import os.path
import glob

env = Environment()

libs = []
libs = ["boost_graph-mt",
        # "boost_test_exec_monitor-mt",
        "boost_unit_test_framework-mt"]


env.Replace(
    CXX = 'clang++',
    CXXFLAGS = '-std=c++14 -stdlib=libc++ -g',
    LINKFLAGS = '-stdlib=libc++'
)
env.Append(CPPPATH = ["/usr/local/include"])
env.Append(LIBPATH = ["/usr/local/lib"])

# env.Append(CPPDEFINES=commonDefines)
# env.Append(CCFLAGS=commonCFlags)
# env.Append(LINKFLAGS=commonLFlags)


for file_path in glob.glob("src/*.cpp"):
    progname = os.path.splitext(os.path.basename(file_path))[0]
    env.Program(progname, [file_path], LIBS=libs)

# env.Program('lc23', ['src/lc23.cpp'], LIBS=libs)
